package:
    name: crbm
    version: "1.0.dev1"

source:
    git_rev: v1.0.dev1
    git_url: https://github.com/wkopp/crbm.git

requirements:
    build:
        - python
        - setuptools
        - sphinx
        - pytest
        - pytest-cov
        - pytest-runner
        - seaborn
        - matplotlib
        - biopython
        - pandas
        - scikit-learn
        - theano
        - joblib
        - weblogo

    run:
        - python
        - theano
        - numpy

test:
    requires:
        - pytest
        - pytest-cov
        - pytest-runner
    imports:
        - crbm
    commands:
        - pip install codecov
        - py.test --cov=./

about:
    home: https://crbm.readthedocs.io
    doc_url: https://crbm.readthedocs.io
    license: GPL-v3
    license_file: LICENSE
